version: '3.7'
services:
  redis:
    image: "redis:7.0.4"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "ping"]
      interval: 30s
      timeout: 3s
      retries: 10
    restart: on-failure
    volumes:
      - redis:/data
    networks:
      - default
    dns:
      - 10.10.1.11
      - 10.11.1.11
      - 10.12.1.11
      - 10.13.1.11
      - 10.14.1.11
      - 10.15.1.11

  mysql:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=scoring_engine
      - MYSQL_USER=se_user
      - MYSQL_PASSWORD=CHANGEME
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    dns:
      - 10.10.1.11
      - 10.11.1.11
      - 10.12.1.11
      - 10.13.1.11
      - 10.14.1.11
      - 10.15.1.11

  nginx:
    image: nginx:1.23.1
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 10
    restart: on-failure
    volumes:
      - ./docker/nginx/files/web.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/files/scoringengine.crt:/etc/nginx/scoringengine.crt
      - ./docker/nginx/files/scoringengine.key:/etc/nginx/scoringengine.key
      - ./scoring_engine/web/static/:/usr/share/nginx/html/static/
    networks:
      - default
    dns:
      - 10.10.1.11
      - 10.11.1.11
      - 10.12.1.11
      - 10.13.1.11
      - 10.14.1.11
      - 10.15.1.11

  base:
    image: scoringengine/base
    build:
      context: .
      dockerfile: ./docker/base/Dockerfile
      cache_from:
        - scoringengine/base
        - base:latest
    dns:
      - 10.10.1.11
      - 10.11.1.11
      - 10.12.1.11
      - 10.13.1.11
      - 10.14.1.11
      - 10.15.1.11

  bootstrap:
    image: scoringengine/bootstrap
    build:
      context: .
      dockerfile: ./docker/bootstrap/Dockerfile
      cache_from:
        - scoringengine/bootstrap
        - bootstrap:latest
    depends_on:
      - base
      - mysql
    healthcheck:
      test: ["CMD", "exit", "1"]
    restart: on-failure
    networks:
      - default
    environment:
      - SCORINGENGINE_EXAMPLE
      - SCORINGENGINE_OVERWRITE_DB
      - SCORINGENGINE_VERSION
    dns:
      - 10.10.1.11
      - 10.11.1.11
      - 10.12.1.11
      - 10.13.1.11
      - 10.14.1.11
      - 10.15.1.11

  engine:
    image: scoringengine/engine
    build:
      context: .
      dockerfile: ./docker/engine/Dockerfile
      cache_from:
        - scoringengine/engine
        - engine:latest
    depends_on:
      - base
      - redis
      - bootstrap
    restart: on-failure
    networks:
      - default
    environment:
      - SCORINGENGINE_EXAMPLE
      - SCORINGENGINE_VERSION
    dns:
      - 10.10.1.11
      - 10.11.1.11
      - 10.12.1.11
      - 10.13.1.11
      - 10.14.1.11
      - 10.15.1.11

  worker:
    image: scoringengine/worker
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
      cache_from:
        - scoringengine/worker
        - worker:latest
    depends_on:
      - base
      - redis
    restart: unless-stopped
    networks:
      - default
    environment:
      - SCORINGENGINE_VERSION
    privileged: true
    dns:
      - 10.10.1.11
      - 10.11.1.11
      - 10.12.1.11
      - 10.13.1.11
      - 10.14.1.11
      - 10.15.1.11

  web:
    image: scoringengine/web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      cache_from:
        - scoringengine/web
        - web:latest
    depends_on:
      - base
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:5000"]
      interval: 30s
      timeout: 3s
      retries: 10
    restart: on-failure
    networks:
      - default
    volumes:
      - injects:/var/uploads/
    environment:
      - SCORINGENGINE_VERSION
    dns:
      - 10.10.1.11
      - 10.11.1.11
      - 10.12.1.11
      - 10.13.1.11
      - 10.14.1.11
      - 10.15.1.11

volumes:
  injects:
  redis:
  mysql:

networks:
  default: